### ISSUE TITLE
I can't install the integration ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by FiftyFour7250** [LAB02-Research/HASS.Agent-Notifier#1]
Hello. For some reason I can't install this integration. HACS just doesn't have it. Then I tried to install manually, but it didn't help either, it doesn't appear after restarting HA. What could be the problem?

**Comment by FiftyFour7250** [comment]
Oh, I had to add this as a custom integration, through three dots in the upper right corner in HACS, and it worked.

**Comment by FiftyFour7250** [comment]
Nah. It still doesn't work. Even though I managed to install the integration, it still doesn't work. This is not in the list of integrations. No new services have appeared. I can't create a notification through this service, because it doesn't exist. Reinstalling via the HACS didn't help((

Here is the video:
https://disk.yandex.ru/i/gA5dSrr4s6tbjg

**Comment by FiftyFour7250** [comment]
Of course, I don't understand much, but isn't it better to use not a separate service for projecting notifications on Windows, but something that will simply reflect persistent notifications? It would work even without the internet.

**Comment by LAB02-Admin** [comment]
Hi @FiftyFour7250, thank you for the extensive report! You can ignore [my reply here](https://github.com/LAB02-Research/HASS.Agent/issues/1), since you already managed to install. 

You have to add the notification entity first, [as described here](https://github.com/LAB02-Research/HASS.Agent-Notifier#configuration):

```yaml
notify: 
  name: "hass agent test device"
  platform: hass_agent_notifier
  resource: http://{device_ip}:5115/notify
```

Restart your Home Assistant instance, and afterwards you can add the new entity in your scripts and automatoins. So you don't have to call the integration directly.

Regarding your persistent notifications tip; this method also doesn't require internet. It goes from your Home Assistant instance directly to your machine, no external servers required. But I do plan on making notifications easier to use - now that this version's released, I'll start looking into better ways that don't require tinkering with ports. Thanks!

**Comment by LAB02-Admin** [comment]
Hi @FiftyFour7250, please remove & reinstall the integration. I noticed Home Assistant didn't like the folder name, so I changed it to be more compliant. After reïnstalling, the snippet I posted will work. 

Be sure to change the IP to your device's ip, and open the port in your firewall. You can run the following command from an elevated promt if you want:

`netsh advfirewall firewall add rule name="HASS.Agent Notifier" dir=in action=allow protocol=TCP localport=5115`

**Comment by FiftyFour7250** [comment]
Yea, thanks it worked.
For posterity: "device IP" - is the local IP address of your computer
To open the port, just run the command prompt as an administrator, and paste the line from the last message

**Comment by LAB02-Admin** [comment]
Good to hear, thanks for the feedback! I'll have a look at the documentation to see if it can be made more clear.
