### ISSUE TITLE
Notification duration option does not work

### ISSUE THREAD

**Issue by LayztrBlueWolf** [LAB02-Research/HASS.Agent-Notifier#13]
Notifications get sent to PC from HA but no matter the value of the duration tag they only persist on screen for about 5 seconds. Is this Windows being windows or is there a problem with said configuration

**Comment by LAB02-Admin** [comment]
> Is this Windows being windows

Haha :p

In Windows 11 there's this setting you could tinker with:

![image](https://user-images.githubusercontent.com/81011038/174978212-a664057d-46fc-4a42-9413-545035978e3c.png)

Haven't changed it myself, no idea if it'll work. I'm planning on switching to my own toast notifications system (as an optional setting) for added flexibility, because yea windows tends to be wIndows and force what it thinks you want.

**Comment by LAB02-Admin** [comment]
Closing this for now, let me know if I can help with anything else (or if this didn't fix it)

**Comment by Boh1** [comment]
After playing with this setting, it appears that the optional duration parameter always gets overridden by whatever the Windows default is set to.

**Comment by MunkeyBalls** [comment]
Duration is also isn't working with Windows 10 and I can't find any place to set the defaults. Also new notifications aren't shown when the old one is still popped up (You do see them in the history however). Cool software, thanks!

**Comment by LAB02-Admin** [comment]
Hey @MunkeyBalls, yea I'm not too happy with the Windows toast notifications. I'll make my own system in a future version.

Cheers, you're welcome :)
